In [ ]:
# even odd
def evenodd(num):
  if num%2==0:
    return True
  else:
    return False

num=int(input("Enter a number:"))
print(evenodd(num))

Enter a number:5
False


In [ ]:
#factotial
def fact(num):
  if num==1 or num==0:
    return 1
  else:
    num=num*fact(num-1)
  return num

num=int(input("Enter a number:"))
print(fact(num))


Enter a number:5
120


In [ ]:
#Print the square of each digit in a list using map function
numbers = [1, 2, 3, 4, 5]
num=map(lambda x:x*x,numbers)
print(list(num))

[1, 4, 9, 16, 25]


In [ ]:
#Print the even numbers in a list using filter function
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
num=filter(lambda x:x%2==0,numbers)
print(list(num))

[2, 4, 6, 8, 10]


In [4]:
#Multiply all the numbers in a list using reduce function
from functools import reduce
numbers = [1, 2.8, 3, 4, 5,17,2]
num=reduce(lambda x,y:x*y,numbers)
print((num))

5711.999999999999


In [ ]:
'''1.Write a Python program to calculate the value of 'a' to the power of 'b' using recursion.
2.Write a Python function to create and print a list where the values are the squares of numbers between 1 and 30
3.Write a Python program to create a dictionary from two lists without losing duplicate values.
Sample lists: ['Class-V', 'Class-VI', 'Class-VII', 'Class-VIII'], [1, 2, 2, 3]
Expected Output: defaultdict(<class 'set'>, {'Class-V': {1}, 'Class-VI': {2}, 'Class-VII': {2}, 'Class-VIII': {3}})'''

In [1]:
def power(a, b):
    if b == 0:
        return 1
    return a * power(a, b - 1)

a = int(input("Enter base (a): "))
b = int(input("Enter exponent (b): "))
result = power(a, b)
print(f"{a} to the power of {b} is: {result}")


Enter base (a): 5
Enter exponent (b): 2
5 to the power of 2 is: 25


In [ ]:
def square():
  l=[]
  for i in range(1,31):
    l.append(i)
  num=map(lambda x:x*x,l)
  print(list(num))

square()

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900]


In [5]:
keys=['Class-V', 'Class-VI', 'Class-VII', 'Class-VIII']
values=[1, 2, 2, 3]

dict1=dict(zip(keys,values))
print(dict1)

{'Class-V': 1, 'Class-VI': 2, 'Class-VII': 2, 'Class-VIII': 3}


In [6]:
keys = ['a', 'b', 'c']
values = [1, 2, 3]

# Using zip() and dict() to create a dictionary
my_dict = dict(zip(keys, values))
print(my_dict)

{'a': 1, 'b': 2, 'c': 3}


#20 march

In [2]:
import numpy as np

In [3]:
l1=[2,3,4]
l2=[6,7,8]
np.array(l1)+np.array(l2)

array([ 8, 10, 12])

In [7]:
l=['apple',6,'Aditya']
t=(5,6,7,8,9)
print(type(l))
print(type(t))

<class 'list'>
<class 'tuple'>


In [9]:
np_l=np.array(l)
np_t=np.array(t)
print(np_l)
print(type(np_l))

print(np_t)
print(type(np_t))

['apple' '6' 'Aditya']
<class 'numpy.ndarray'>
[5 6 7 8 9]
<class 'numpy.ndarray'>


In [12]:
matrix1=[[1,2],[4,5],[1,8]]
mat=np.array(matrix1)
type(mat)

numpy.ndarray

In [16]:
mat

(3, 2)

In [17]:
mat.shape

(3, 2)

In [20]:
arr2=np.arange(0,10,3)#return int values at equal space intervals
print(arr2)

[0 3 6 9]


In [40]:
matrix1=np.linspace(1,30,30) #return float values at equal space intervals
matrix1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30.])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
mat3=np.zeros([4,5])
mat3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
mat4=np.ones([3,2]) #1. is bcoz of mathematical function with another matrix and bydefault
mat4

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
mat5=np.eye(5) # diagonal 1 in matrix
mat5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
matrix1 =matrix1.reshape(1,30)
print(matrix1)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]


In [49]:
matrix1 = matrix1.reshape(6,5)
print(matrix1)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]
 [26. 27. 28. 29. 30.]]
